### ISSUE TITLE
Recording only top left corner of the screen

### ISSUE THREAD

**Issue by tnfssc** [SamuelScheit/puppeteer-stream#101]
When I run it on Macbook, it runs fine and records correctly, in the resolution I specify.
When I run it on Docker, it runs, but it only records the top left corner of the screen. And the resolution is also smaller. It cropped into the top left corner. It captures just about a quarter of the screen. I observed that when I deleted the line `defaultViewport: { height: 900, width: 1440 },`, the recording was fine, but the resolution still was low (same size as cropped top left corner case). I use headless, so I don't think not having a display is the problem

Here's the relevant code snippets:

```ts
        puppeteer.use(StealthPlugin());
        puppeteer.use(new SessionPlugin());
        const puppeteerArgs = [
            "--window-size=1440,900",
            "--start-maximized",
            "--no-sandbox",
            "--disable-dev-shm-usage",
            "--media-cache-size=0",
            "--disk-cache-size=0",
            "--headless=new",
        ];
        const options: Parameters<typeof puppeteer.launch>[0] = {
            defaultViewport: { height: 900, width: 1440 },
            args: puppeteerArgs,
            handleSIGINT: false,
            handleSIGTERM: false,
        };
        const browser: Browser = await launch(puppeteer, options);
        const page = await browser.newPage();
        await (await page.target().createCDPSession()).send("Emulation.clearDeviceMetricsOverride");
        const stream = await getStream(this.page, {
            audio: true,
            video: true,
            // audioBitsPerSecond: 128000,
            // videoBitsPerSecond: 2500000,
            // bitsPerSecond: 2620000,
            // videoConstraints: {
            //     mandatory: {
            //         width: 1440, // I tried changing these too. But no change 😢 
            //         height: 900,
            //         frameRate: 12,
            //     },
            // },
            // frameSize: 1000,
        });
        const file = fs.createWriteStream(filename);
        stream.pipe(file);
```

**Comment by AustinGomez** [comment]
I fixed this by adding:

```
  await page.setViewport({
    width: 1920,
    height: 1080,
    deviceScaleFactor: 1,
  });
```

**Comment by tnfssc** [comment]
@AustinGomez I removed the `defaultViewport` and added the `page.setViewport` as you told. It recorded the whole page. But the resolution of the output video is not what I set the `width` and `height` as. The resolution of the output video seems to be fixed at 800x600, even if I set them to 1440x900 everywhere. I tried again with `defaultViewport`, with 1440x900. The output video's resolution is still the same, but this time it cropped into the top left 800x600. I tried with 2560x1440, it cropped to the top left 800x600 again.

Here's an `ffprobe` if that's helpful

```txt
ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.0 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[matroska,webm @ 0x150804080] Length 5 indicated by an EBML number's first byte 0x0d at pos 1430957 (0x15d5ad) exceeds max length 4.
Input #0, matroska,webm, from './out.webm':
  Metadata:
    encoder         : Chrome
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
  Stream #0:1(eng): Video: vp8, yuv420p(tv, bt709, progressive), 800x600, SAR 1:1 DAR 4:3, 60 tbr, 1k tbn (default)
    Metadata:
      alpha_mode      : 1
```

**Comment by nivhsay** [comment]
Ozone used on Linux by the new headless is causing your issue.

See https://github.com/puppeteer/puppeteer/issues/10243#issuecomment-1584377903

**Comment by tnfssc** [comment]
> Ozone used on Linux by the new headless is causing your issue.
> 
> See https://github.com/puppeteer/puppeteer/issues/10243#issuecomment-1584377903

It works. Thanks a lot. Closing the issue.

**Comment by mchusma** [comment]
Just noting in case this is helpful to someone else. I had to adjust window-size, ozone, and not use default viewport in order to get mine to work right, and guess and check the window size to get it right.

async function test() {
  const browser = await launch({
    executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    headless: true,
    //if there are black bars on the side or top, adjust the window size.
    args: ['--window-size=1280,849', '--use-gl=angle', '--use-angle=gl-egl', '--headless=new', '--start-fullscreen', '--no-sandbox', '--disable-setuid-sandbox', `--ozone-override-screen-size=1280,720`   ],
  });
