### ISSUE TITLE
Can 'highWaterMark' support configuration

### ISSUE THREAD

**Issue by dingqiaolin** [SamuelScheit/puppeteer-stream#111]
![image](https://github.com/SamuelScheit/puppeteer-stream/assets/121471336/8baf3284-6bfe-4168-9736-74ad4d4be37e)
The pages I record sometimes lose frames, and I suspect that the 'highWaterMark' configuration is too small. Can this parameter be released to support configuration?

**Comment by nivhsay** [comment]
I experience the same at times.
Did it help when you increased it?

**Comment by dingqiaolin** [comment]
I tried it, but it didn't have much effect. I need to see if it's affected by other factors

**Comment by dingqiaolin** [comment]
![image](https://github.com/SamuelScheit/puppeteer-stream/assets/121471336/f65b3083-7b4e-4bdb-8879-f7b9f85e7e84)
I found that there is a problem with sending data through udp. Changing udp to a method of registering and sending data would be much more stable.

**Comment by SamuelScheit** [comment]
Yes we need to change the data transmission method, what do you suggest to use instead?

**Comment by nivhsay** [comment]
I recently patched the module on my setup to use tcp and it's working well.

**Comment by SamuelScheit** [comment]
Awesome @nivhsay can you create a PR?
