### ISSUE TITLE
Headless recording

### ISSUE THREAD

**Issue by SaadAI2** [SamuelScheit/puppeteer-stream#124]
Is it possible to record audio and video in headless mode? If not, what is the optimal platform for deploying an application that requires a headful browser with audio and video capabilities?

**Comment by pbkompasz** [comment]
I managed to record video in headless mode with the following script.
Not sure if it records audio.

``` js
const { launch, getStream } = require("puppeteer-stream");
const Xvfb = require('xvfb');

const file = fs.createWriteStream(`./example.mp4`);
var xvfb = new Xvfb({
  silent: true,
  xvfb_args: ["-screen", "0", '1920x1080x30', "-ac"],
});
xvfb.start((err) => { if (err) console.error(err) })

const browser = await launch({
  executablePath: 'google-chrome',
  headless: false,
  defaultViewport: null,
  protocolTimeout: 30000,
  args: ['--no-sandbox', '--start-fullscreen', '--display=' + xvfb._display,
    '--window-size=1920,1080',],
});

const page = await browser.newPage();
const stream = await getStream(page, { audio: true, video: true });

stream.pipe(file);

// ...

await stream.destroy();
file.close();
xvfb.stop();
```

**Comment by xephtar** [comment]
did you guys tried it on k8s clusters? i mean in a pod

**Comment by unravelers-tech** [comment]
> puppeteer-stream could record audio and video at the same time, even in headless mode. i've already used it in production

Could you tell me how you achieved it? The code has `headless = false` hardcoded. Which workaround you've used?

**Comment by unravelers-tech** [comment]
> I managed to record video in headless mode with the following script. Not sure if it records audio.
> 
> ```js
> const { launch, getStream } = require("puppeteer-stream");
> const Xvfb = require('xvfb');
> 
> const file = fs.createWriteStream(`./example.mp4`);
> var xvfb = new Xvfb({
>   silent: true,
>   xvfb_args: ["-screen", "0", '1920x1080x30', "-ac"],
> });
> xvfb.start((err) => { if (err) console.error(err) })
> 
> const browser = await launch({
>   executablePath: 'google-chrome',
>   headless: false,
>   defaultViewport: null,
>   protocolTimeout: 30000,
>   args: ['--no-sandbox', '--start-fullscreen', '--display=' + xvfb._display,
>     '--window-size=1920,1080',],
> });
> 
> const page = await browser.newPage();
> const stream = await getStream(page, { audio: true, video: true });
> 
> stream.pipe(file);
> 
> // ...
> 
> await stream.destroy();
> file.close();
> xvfb.stop();
> ```

For some reason the example doesn't seem to work. It says
```
Error: spawn Xvfb ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn Xvfb',
  path: 'Xvfb',
  spawnargs: [ ':99', '-screen', '0', '1080x1920x30', '-ac' ]
}
```

**Comment by SamuelScheit** [comment]
by adding this cli argument to the browser args, `--headless=new`

**Comment by unravelers-tech** [comment]
@SamuelScheit okay. I deleted my post to provide the answer.

These settings worked for me:

```
const browser = await launch({
  executablePath: executablePath(),
  defaultViewport: {
    width: 1080,
    height: 1920,
  },
  args: [
    '--headless=new',
    '--no-sandbox',
    '--window-size=1080,1920',
    '--disable-setuid-sandbox',
    '--ozone-override-screen-size=1080,1920',
  ],
});
 ```
 
 @xephtar tested in GCP. Worked well.
 
 Minimum instance requirements - 16Gib and 2 CPUs. If less, the video had cracks and freezes.

**Comment by SaadAI2** [comment]
> I managed to record video in headless mode with the following script. Not sure if it records audio.
> 
> ```js
> const { launch, getStream } = require("puppeteer-stream");
> const Xvfb = require('xvfb');
> 
> const file = fs.createWriteStream(`./example.mp4`);
> var xvfb = new Xvfb({
>   silent: true,
>   xvfb_args: ["-screen", "0", '1920x1080x30', "-ac"],
> });
> xvfb.start((err) => { if (err) console.error(err) })
> 
> const browser = await launch({
>   executablePath: 'google-chrome',
>   headless: false,
>   defaultViewport: null,
>   protocolTimeout: 30000,
>   args: ['--no-sandbox', '--start-fullscreen', '--display=' + xvfb._display,
>     '--window-size=1920,1080',],
> });
> 
> const page = await browser.newPage();
> const stream = await getStream(page, { audio: true, video: true });
> 
> stream.pipe(file);
> 
> // ...
> 
> await stream.destroy();
> file.close();
> xvfb.stop();
> ```

This is working for me on Linux server .

**Comment by nimit45** [comment]
> defaultViewport: {
>     width: 1080,
>     height: 1920,
>   },
>   args: [
>     '--headless=new',
>     '--no-sandbox',
>     '--window-size=1080,1920',
>     '--disable-setuid-sandbox',
>     '--ozone-override-screen-size=1080,1920',
>   ],

Worked for me
