### ISSUE TITLE
ffmpeg not working

### ISSUE THREAD

**Issue by yashkhandelwal05** [SamuelScheit/puppeteer-stream#128]
I have tried out both ffmpeg.kill() and ffmpeg.stdin.destroy() But still it's not working.

**Comment by SamuelScheit** [comment]
I found a fix, you need to manually close the stdin stream, after the tab stream was closed:
```js
stream.on("close", () => {
	ffmpeg.stdin.end();
});
```

**Comment by yashkhandelwal05** [comment]
What is the use of the close callback for stream ?
Will the await stream.destroy() line take time to close off the stream?

**Comment by SamuelScheit** [comment]
yes, it does. The stream has a delay of ~a second and it waits for the stream to end and send the last packet, until it closes the stream

**Comment by yashkhandelwal05** [comment]
For longer duration videos>= 15 mins it's not working. The stream close is working but ffmpeg.stdin.end() is not working and I am not getting a close callback.
await new Promise((resolve) => {
            ffmpeg.stdin.end();
            ffmpeg.on('close', (code) => {
              console.log(`FFmpeg process exited with code ${code}`);
              resolve();
            });
          });

**Comment by yashkhandelwal05** [comment]
CPU Utilization with exec is also very high

**Comment by yashkhandelwal05** [comment]
Can you please try removing this part:
ffmpeg.stderr.on("data", (chunk) => {
console.log(chunk.toString());
});
And check whether it's working or not

**Comment by yashkhandelwal05** [comment]
There is also problem with this line:
const ffmpeg = exec(`ffmpeg -y -i - -c copy output.mp4`);
I am getting this error. Can you please check?

![WhatsApp Image 2023-08-08 at 1 17 54 PM](https://github.com/SamuelScheit/puppeteer-stream/assets/68495722/d13fc057-ed20-4de6-90f2-a7de03f04481)

**Comment by yashkhandelwal05** [comment]
@SamuelScheit any update?

**Comment by SamuelScheit** [comment]
works for me
