### ISSUE TITLE
Shutdown is taking more than 5 seconds

### ISSUE THREAD

**Issue by RobertoUa** [SamuelScheit/puppeteer-stream#131]
The issue is with this setTimeout. Please add `.unref()` so that exit is not delayed.
Browser and ffmpeg is already closed so there no need to wait for this
https://github.com/SamuelScheit/puppeteer-stream/blob/main/src/PuppeteerStream.ts#L186

**Comment by RobertoUa** [comment]
at least make the timeout configurable

**Comment by RobertoUa** [comment]
and you can also check if socket is already closed before creating timeout

**Comment by SamuelScheit** [comment]
Done in `puppeteer-stream@3.0.7`:
```js
const stream = getStream(page, { 
  streamConfig: {
    closeTimeout: 5000
  }
})
```

**Comment by RobertoUa** [comment]
btw, since we're talking about script closing, I sometimes get `(Runtime.callFunctionOn): Target closed` when `extension.evaluate((index) => STOP_RECORDING(index), index)` is run.
I belive you can a catch there.

**Comment by RobertoUa** [comment]
this is great! thank you so much! Especially for the fastest response ever!
The requirement of my app is to shutdown as fast as possible when everything is processed (ffmpeg was already closed at that point and video produced)

**Comment by RobertoUa** [comment]
can you please catch errors in `extension.evaluate((index) => STOP_RECORDING(index), index)`
I get this most of the time
```
uncaughtException: Protocol error (Runtime.callFunctionOn): Target closed
TargetCloseError: Protocol error (Runtime.callFunctionOn): Target closed
```
