### ISSUE TITLE
Electron build fails to access stream extension workaround

### ISSUE THREAD

**Issue by jmalfara** [SamuelScheit/puppeteer-stream#137]
Im leaving this here more as a reference. When creating an asar packed electron build this library gets bundled into the asar by default. Normally thats fine but `node_modules/puppeteer-stream/extensions` needs to be available externally so it can be loaded into Chrome. 

Adding `asarUnpack` to the electron config is expected like so
```
  asarUnpack: [
    ....
    'node_modules/puppeteer-stream',
  ],
``` 

But we also need to manually replace the path located in `node_modules/puppeteer-stream/dist/PuppeteerStream.js` during build time.
```  
  // Fix Puppeteer Extension Visibility
  const puppeteerStreamDist = fs.readFileSync(
    'node_modules/puppeteer-stream/dist/PuppeteerStream.js',
    'utf-8'
  ).replace(
    'path.join(__dirname, "..", "extension");',
    'path.join(__dirname.replace("app.asar", "app.asar.unpacked"), "..", "extension");'
  )

  fs.writeFileSync(
    'node_modules/puppeteer-stream/dist/PuppeteerStream.js',
    puppeteerStreamDist
  )
```

Again just leaving this here as a reference but really not too sure what could be done. Maybe we could expose another parameter to override the extension path.

**Comment by tarikhagustia** [comment]
hi @jmalfara where can I put the replace script?
