### ISSUE TITLE
Want to run two recordings simultaneously

### ISSUE THREAD

**Issue by nodminger** [SamuelScheit/puppeteer-stream#139]
How can I record two streams simultaneously? When I do with normal code I get error as `Error: listen EADDRINUSE: address already in use :::55200`. I tried [this](https://github.com/SamuelScheit/puppeteer-stream/issues/109#issuecomment-1610305863) but still not able to do it. Is there any way to record simultaneously?

**Comment by jmalfara** [comment]
If you search for that port in the src. It seems to be to the websocket port for the extension.
From a quick glance it doesn't look configurable. Perhaps it can be made to be configurable

[extension/options.js](https://github.com/SamuelScheit/puppeteer-stream/blob/1204241ba4b01bf7049d46a7170ede12c756c8c0/extension/options.js#L32)

**Comment by ddaydd** [comment]
I don't understand, I record several streams at the same time without any error...

**Comment by nodminger** [comment]
> I don't understand, I record several streams at the same time without any error...

How did you open multiple browsers tabs in same browsers?

**Comment by ddaydd** [comment]
I have not tested in the same browser...
