### ISSUE TITLE
Unable to access Dialog in pupetter stream

### ISSUE THREAD

**Issue by nbalasubramanianwaymore** [SamuelScheit/puppeteer-stream#160]
Can you let me know or provide me a way to access dialogs in pupetter stream as we do in pupetter
Do we have anything like this
 page.on('dialog', async dialog => {
      //get alert message
      console.log(dialog.message());
      //accept alert
      await dialog.accept();
   })

Can someone help me on this

**Comment by SamuelScheit** [comment]
Yes puppeteer stream just returns a puppeteer browser instance that you can use to access dialogs.

https://pptr.dev/api/puppeteer.dialog


```ts
import { launch } from 'puppeteer-stream';

(async () => {
  const browser = await launch({});
  const page = await browser.newPage();
  page.on('dialog', async dialog => {
    console.log(dialog.message());
    await dialog.dismiss();
    await browser.close();
  });
  page.evaluate(() => alert('1'));
})();
```

**Comment by nbalasubramanianwaymore** [comment]
In my case , we get a dialog in the teams opening right? "Do you want to join the meet in browser or app?" I'm unable to access this alert with the above code.

I have attached the popup image which I need to access.

Can you let me know on this?
![teams_popup](https://github.com/SamuelScheit/puppeteer-stream/assets/170104685/8a18f0a8-cf29-42a6-adbd-264a67dd7ba9)

**Comment by SamuelScheit** [comment]
Sorry, but I I don't have the time to fix your specific MS teams bug, which is not part of the library.
Consider [sponsoring](https://github.com/sponsors/SamuelScheit) or [hiring](https://samuelscheit.com/) me so I can help you.
