### ISSUE TITLE
Bad audio recorded

### ISSUE THREAD

**Issue by GilDansou** [SamuelScheit/puppeteer-stream#161]
I always got this kind of audio. Any idea how to fix it ?
[6654c874eaa8d3532be36d2a.webm](https://github.com/SamuelScheit/puppeteer-stream/assets/117546858/d8391efb-066c-4add-88ea-a4bd7c43a5fe)

**Comment by SamuelScheit** [comment]
Does this happen only on the server or also on your local development setup?

If it only happens on the server, it might be overloaded and doesn't have enough resources

**Comment by GilDansou** [comment]
It happens only on my local development

**Comment by GilDansou** [comment]
Do you know what can cause this?
