### ISSUE TITLE
Chrome Extension Error When Packaging with Electron as a DMG File

### ISSUE THREAD

**Issue by Mrkk1** [SamuelScheit/puppeteer-stream#168]
This library has been incredibly helpful to me, but I’ve encountered a very tricky issue that I can’t resolve. I used Electron to package my application, and while everything works perfectly in serve mode, the packaged application throws an error upon launch.
After packaging my application as a DMG file with Electron, I encounter an error when launching Chrome within the application. The error seems to be related to the inability to find or load a Chrome extension.
<img width="260" alt="image" src="https://github.com/user-attachments/assets/e76b0393-8266-4859-a7df-33f6ce8b0947">
<img width="448" alt="image" src="https://github.com/user-attachments/assets/015cfe53-2713-4df8-89fb-509373b01b0c">

**Comment by SamuelScheit** [comment]
#137
