### ISSUE TITLE
When I was recording using steem, there was an error when calling page.screenshot

### ISSUE THREAD

**Issue by Mrkk1** [SamuelScheit/puppeteer-stream#172]
Description: I used streem to record webm, and then took a screenshot at a certain moment. I was surprised by the results of the screenshot. Sometimes it was normal, but sometimes he could only intercept a certain part of the upper left corner.
And I checked the webm transcription results and found that the page changed at the moment of the screenshot, which seemed to have been zoomed in or out.

Below is the relevant code:

```js
  let browser = await launch({
    headless: "new",

    userDataDir,
    defaultViewport: { width: 1920, height: 1180 },

    args: [
      "--disable-web-security",
      "--allow-file-access-from-files",
      "--no-sandbox",
      "--disable-setuid-sandbox",
      `--ozone-override-screen-size=1920,1080`,
      `--window-size=1920,1080`,
    ],
    channel: "chrome",
  });

  page = await browser.newPage();

  await page.setViewport({
    width: 1920,
    height: 1080,
  });
  
//  ========================================>>>>

 const stream = await getStream(page, {
      audio: true,
      video: true,
      audioBitsPerSecond: 128000,
      videoBitsPerSecond: 6000000,
      videoConstraints: {
        mandatory: {
          minWidth: 1920,
          minHeight: 1080,
          maxWidth: 1920,
          maxHeight: 1080,
          minFrameRate: 25,
        },
      },
    });

// ===========================================>>>

await page.screenshot({
    path: filePath,
    captureBeyondViewport: true
 
  });
  
```

  I tried to modify captureBeyondViewport, but nothing worked

**Comment by SamuelScheit** [comment]
Sorry, but this issue is not relevant to puppeteer-stream.

However here are are some things you can investigate:
- Maybe it is an issue with the website, does this behaviour also occur with other sites?
- What parameters does page.screenshot accept and does the behaviour differ with different params?
- Is the page scaling/screensize relevant for this issue?
