### ISSUE TITLE
Webm File metadata missing

### ISSUE THREAD

**Issue by msaad117** [SamuelScheit/puppeteer-stream#176]
const filename = `./${emailName}+${uuidv4()}.webm`;
const file = fs.createWriteStream(filename);
 stream = await getStream(page, {
            audio: true,
            video: true,
            frameSize: 25,
            mimeType: "video/webm;codecs=vp8",
            audioBitsPerSecond: 128000,
            videoBitsPerSecond: 2500000,
            videoConstraints: {
              mandatory: {
                minWidth: 1920,
                minHeight: 1080,
                maxWidth: 1920,
                maxHeight: 1080,
              },
            },
          });
  
          console.log("Recording", stream);
          stream.pipe(file);
          
          I'm using Puppeteer-Stream to capture the stream from a Google Meet session, but the metadata is missing from the output file. I'm converting the WebM file to MP4 using Fluent-FFmpeg, but the conversion is very slow—taking about 50 minutes for a 100 MB file. Is there a way to retain the metadata in the WebM file?

**Comment by SamuelScheit** [comment]
It is a known issue by the browsers MediaRecorder.
  
https://github.com/collab-project/videojs-record/issues/317
https://bugzilla.mozilla.org/show_bug.cgi?id=1068001

However there are libraries which can add metadata to webm files, see this issue comment:
https://github.com/collab-project/videojs-record/issues/317#issuecomment-452130902
