### ISSUE TITLE
Have output video appear as normal video file

### ISSUE THREAD

**Issue by StianWiu** [SamuelScheit/puppeteer-stream#19]
I understand this might be on purpose to allow easier streaming on websites but I'm not using it for a website and there aren't really any other good alternatives. Is there any way to either convert the file or toggle on/off so it won't be endless?

Anyways I love the project it works great for what it is supposed to do.

**Comment by Flam3rboy** [comment]
This is because the MediaRecorder of chrome only is able to record webm video.
You need to convert it with [ffmpeg](https://github.com/Flam3rboy/puppeteer-stream/blob/main/examples/ffmpeg.js). See #14 and #9

**Comment by Pignuuu** [comment]
One last thing. ffmpeg is absolutely tanking my cpu. I tried adding '-threads 1' but it hasn't made a dent. Know of any ways to minimize cpu usage?

``` typescript
const ffmpeg = exec(`ffmpeg -y -threads 1 -i - ./videos/${filename}-export.mp4`);
```
