### ISSUE TITLE
[Question] Using puppeteer-extra plugins

### ISSUE THREAD

**Issue by brodysctt** [SamuelScheit/puppeteer-stream#24]
Would love to use the [adblocker plugin](https://github.com/berstend/puppeteer-extra/tree/95e0b260c8be0c7f88ae2058dadad454156783bb/packages/puppeteer-extra-plugin-adblocker) for my current project, and the [stealth plugin](https://github.com/berstend/puppeteer-extra/tree/95e0b260c8be0c7f88ae2058dadad454156783bb/packages/puppeteer-extra-plugin-stealth) for my next one.

I tried making a few adjustments to `PuppeteerStream.ts`:

```
import { LaunchOptions, Browser, Page, BrowserOptions, ChromeArgOptions } from "puppeteer";
import puppeteer from 'puppeteer-extra'
import Adblocker from 'puppeteer-extra-plugin-adblocker'
```

```
puppeteer.use(AdblockerPlugin()) // Added before the browser is initialized on line 69.
```

The result is an indefinitely loading blank tab – any ideas on how I could get it to work?

**Comment by Flam3rboy** [comment]
How do you start the puppeteer browser? Can you show your launch code

**Comment by bscott4** [comment]
I'm just running the `file.js` example as is – no changes made there

**Comment by stevebutterworth** [comment]
Any progress on this? I love the extension but need to be able to use it with puppeteer-extra too.

**Comment by alan1420** [comment]
#48

**Comment by SamuelScheit** [comment]
Have a look at the [example file](https://github.com/SamuelScheit/puppeteer-stream/blob/main/examples/puppeteer-extra.js).
