### ISSUE TITLE
Recording is taking alot of CPU

### ISSUE THREAD

**Issue by varunk29** [SamuelScheit/puppeteer-stream#43]
is there any way to optimize it, it seems to take a lot of CPU when I start recording,

- I tried lowering the resolution to 720p from 1080p, it takes a bit less CPU usage m but it is still high
@Flam3rboy  thanks for the repo

**Comment by Flam3rboy** [comment]
If you don't need audio, I recommend the chrome dev tools screencast API, which has better performance and the [puppeteer-screen-recorder](https://www.npmjs.com/package/puppeteer-screen-recorder).

**Comment by varunk29** [comment]
ill need audio, I'm trying to record a webrtc call

**Comment by varunk29** [comment]
I see you're using an extension for recording audio and video, 
- can the extensions work on headless mode?

**Comment by Flam3rboy** [comment]
#4

**Comment by megan0n** [comment]
In ```PuppeteerStream.js```, ```opts.frameSize``` is set to ```20``` by default.
It is then passed to```extension/background.js``` where it is consumed by ```recorder.start(opts.framesize)```.
Set ```opts.frameSize``` to >= ```1000```. It should generate a Blob every 1000ms, not every 20ms.

**Comment by varunk29** [comment]
I tried that, but it still didn't help in reducing CPU usage

**Comment by SamuelScheit** [comment]
I've rewritten the transmission method in c420bc4 and it should now use a lot less CPU
