### ISSUE TITLE
Reduce recording time

### ISSUE THREAD

**Issue by atulmy** [SamuelScheit/puppeteer-stream#49]
Currently to record a video of 5 minutes, we've to set time out for 300000, which is not really efficient. Is there a way to speed up the task, for example speeding up internal recording so that if there is enough machine resources, the recording for 5 min video is actually finished in 30 seconds?

Any help or thoughts would be really appreciated.

**Comment by Flam3rboy** [comment]
The plugin just records the browser window, so if you would want to speed up the recording you would have to increase the fps and e.g. speed up the video/animation that are playing in the browser.
