### ISSUE TITLE
Fixed duration of videos  

### ISSUE THREAD

**Issue by DantrazTrev** [SamuelScheit/puppeteer-stream#57]
Currently recording to a file using timeout as a measure leads to inaccurate video lengths depending on the processing that needs to be done . Can there be any alternative here ?

**Comment by JijaProGamer** [comment]
Can you use ffprobe to get the duration writen to the file metadata? Also, you can try to re-encode it using ffmpeg since that most of the time solves issues with duration for me.

**Comment by SamuelScheit** [comment]
You can use the [fix-webm-duration](https://www.npmjs.com/package/fix-webm-duration) package to fix the duration of the webm output file.
