### ISSUE TITLE
[Question] How to pause recording on media buffering and re-record after media is loaded 

### ISSUE THREAD

**Issue by PradyumnTiwari** [SamuelScheit/puppeteer-stream#60]
Hello team,
Thank you so much for this awesome NPM.
Currently, I am facing an issue, which is -  I am recording and video by HTML video editor (which is developed by my team), there are lots of media is running at the same time. The issue is when I am recording the video, my media is buffering to load in the browser and it is also recorded, so I want to pause the recording on buffering time, and after properly loading my media starts re-recording.

Please suggest to me how to pause recording for some time and start it again.
Please let me know if any input you need from my end.

Thanks in advance :)

**Comment by Flam3rboy** [comment]
It could be possible to use the .pause() function of the MediaRecorder api, which this package uses to record the webpage:
https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/pause
But you would have to look into the source code of this package to make it work.
