### ISSUE TITLE
[QUESTION] How to stop recording on button click

### ISSUE THREAD

**Issue by Sed9yDataBank** [SamuelScheit/puppeteer-stream#64]
Puppeteer navigates to a certain web page and starts recording it. I want to be able to stop the recording when an external user click on a button on that certain webpage. Is This possible? (I tried setting an Event Listener but it doesn't work)

Currentley in README there is this but it is not what I want / stopping the recording with`setTimeout`

```js
stream.pipe(file);
	setTimeout(async () => {
		await stream.destroy();
		file.close();
		console.log("finished");
	}, 1000 * 10);
```

**Comment by SamuelScheit** [comment]
You could expose a function from node inside the browser process and then stop the stream on invocation:
```js
page.exposeFunction("buttonSubmit", () => {
    stream.destroy()
})
```

and inside the page you have a button
```html
<button onclick="buttonSubmit()" />
```
