### ISSUE TITLE
Record multiple pages at the same time

### ISSUE THREAD

**Issue by stefantofan** [SamuelScheit/puppeteer-stream#67]
Is it possibles to record multiple pages at the same time ? If so, how can i accomplish this?

**Comment by SamuelScheit** [comment]
Yes, I've refactored a lot of the code and it is possible now.
You just open multiple pages at once and open a stream for each of them.
Have a look at the [server example](https://github.com/SamuelScheit/puppeteer-stream/blob/main/tests/server.js).
