### ISSUE TITLE
getStream is not work

### ISSUE THREAD

**Issue by liyikun** [SamuelScheit/puppeteer-stream#69]
```

const { launch, getStream } = require("puppeteer-stream");
const fs = require("fs");


 const browser = await launch({
    ignoreHTTPSErrors: true,
    executablePath: '/Applications/Google Chrome 2.app/Contents/MacOS/Google Chrome',
    args: [
       "--no-sandbox",
       "--autoplay-policy=no-user-gesture-required",
       "--disable-web-security",
    ],
    defaultViewport: {
        width: 800,
        height: 1280,
    },
  });
  
  const page = await browser.newPage();

  page.on('console', msg => console.log('PAGE LOG:', msg.text()));

  await page.goto('xxxxx')

  console.log("recording");

  const stream = await getStream(page, { audio: true, video: true });

  console.log("recording2");
```
"recording2" do not print, because getStream method is block.

**Comment by liyikun** [comment]
Apple M1 Pro

**Comment by liyikun** [comment]
browser  101.0.4951.64

**Comment by JijaProGamer** [comment]
My problem resolved when I deleted all my args and ignoreHTTPSErrors. Can you try that and tell me if it works?

**Comment by liyikun** [comment]
> 

it works, but i need there args.

**Comment by liyikun** [comment]
> My problem resolved when I deleted all my args and ignoreHTTPSErrors. Can you try that and tell me if it works?

it works, but i need there args.

**Comment by liyikun** [comment]
> My problem resolved when I deleted all my args and ignoreHTTPSErrors. Can you try that and tell me if it works?

Is there anything else you can do?

**Comment by liyikun** [comment]
@Flam3rboy hi, Have you ever met

**Comment by romain130492** [comment]
`--disable-web-security` when ON doesnt work with that package for some weird reason, any idea @Flam3rboy ?

**Comment by paulnen** [comment]
it seems like an executablePath is required to be able to record directly in webm

`const { executablePath } = require('puppeteer');
const browser = await launch({
    executablePath: executablePath()
  });`

**Comment by SamuelScheit** [comment]
Could you try it with the latest puppeteer version, I've refactored a lot to improve performance and reliability.
```
npm i puppeeteer-stream@latest
```
