### ISSUE TITLE
Is it possible to record multiple streams from a same tab

### ISSUE THREAD

**Issue by varunk29** [SamuelScheit/puppeteer-stream#70]
Hey, @Flam3rboy hope you doing great.

I'm trying to record audio and video files separately
For video
`this.stream = await getStream(this.page, {
                    audio: true, video: true
 });`
this.stream.pipe(this.file);

For Audio
`this.audioStream = await getStream(this.page, {
                    audio: true, video: false
 });`

but I noticed the video file is empty, can tabCapture be called twice in a single tab?

**Comment by SamuelScheit** [comment]
No sadly not, the tabCapture api only allows one concurrent stream at the time. This is a limitation of the browser
