### ISSUE TITLE
How do I set or determine the sample rate for an audio stream?

### ISSUE THREAD

**Issue by darloski** [SamuelScheit/puppeteer-stream#71]
I am trying to set or determine the sample rate for the audio stream being captured but have no idea. Where or how can I determine that value?

thanks

**Comment by SamuelScheit** [comment]
You can specify all [MediaRecorder](https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API) and [tabCapture](https://developer.chrome.com/docs/extensions/reference/tabCapture/#type-CaptureOptions) options.
Install the latest version:
```
npm i puppeteer-stream@latest
```

To set the audio sample rate:
```js
getStream(page, {
    audioConstraints: {
        mandatory: {
            sampleRate: { exact: 48000 }
        }
    }
}) 
```
