### ISSUE TITLE
No audio stream

### ISSUE THREAD

**Issue by eldhoz515** [SamuelScheit/puppeteer-stream#87]
Only video is getting recorded, no audio.

const { launch, getStream } = require("puppeteer-stream");
const fs = require("fs");

const file = fs.createWriteStream("test.webm");

async function test() {
    const browser = await launch({
        defaultViewport: {
            width: 1920,
            height: 1080,
        },
        executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe"
    });

    const page = await browser.newPage();
    await page.goto("https://localhost:5115");
    const stream = await getStream(page, { audio: true, video: true});
    console.log("recording");

    stream.pipe(file);
    setTimeout(async () => {
        await stream.destroy();
        file.close();
        browser.close();
        console.log("finished");
    }, 1000 * 5);
}

test();

**Comment by eldhoz515** [comment]
vs code player fooled me, audio was there... :(

**Comment by shozabnadeem1** [comment]
@eldhoz515 us moment bro
