### ISSUE TITLE
Returning 0kb or empty test.webm file

### ISSUE THREAD

**Issue by ManishAqua** [SamuelScheit/puppeteer-stream#90]
Hi, I tried recording my google meet using the package.
I am using chromium as my puppeteer browser.
On executing the script, puppeteer-stream is giving me test.webm file which is empty or 0kb file.
I am putting my script for the reference.

`import puppeteer from 'puppeteer-extra';
import StealthPlugin from 'puppeteer-extra-plugin-stealth';
import { executablePath } from 'puppeteer';
import fs from 'fs';
import AudioRecorder from 'node-audiorecorder';
import * as PuppeteerScreenRecorder from 'puppeteer-screen-recorder'
import RecordRTC from 'recordrtc';

import { getStream } from "puppeteer-stream";

const file = fs.createWriteStream("./test.webm");

puppeteer.use(StealthPlugin());
(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    defaultViewport: null,
    devtools: false,
    args: [
      "--window-size=1920,1080",
      "--window-position=1921,0",
      "--autoplay-policy=no-user-gesture-required",
    ],
    ignoreDefaultArgs: ["--mute-audio"],
    executablePath: executablePath(),
  });

  const page = await browser.newPage();
  const navigationPromise = page.waitForNavigation();
  const context = browser.defaultBrowserContext();

  await context.overridePermissions(
    "https://meet.google.com/", ["microphone", "camera", "notifications"]
  );

  // going to Meet after signing in
  await page.waitForTimeout(2500);
  await page.goto('https://meet.google.com/qbg-mqks-fqq' + '?hl=en', {
    waitUntil: 'networkidle0',
    timeout: 10000,
  });

  await navigationPromise;

  await page.waitForSelector('input[aria-label="Your name"]', {
    visible: true,
    timeout: 50000,
    hidden: false,
  });

  // turn off cam using Ctrl+E
  await page.waitForTimeout(1000);
  await page.keyboard.down('ControlLeft');
  await page.keyboard.press('KeyE');
  await page.keyboard.up('ControlLeft');
  await page.waitForTimeout(1000);

  //turn off mic using Ctrl+D
  await page.waitForTimeout(1000);
  await page.keyboard.down('ControlLeft');
  await page.keyboard.press('KeyD');
  await page.keyboard.up('ControlLeft');
  await page.waitForTimeout(1000);

  //click on input field to enter name
  await page.click(`input[aria-label="Your name"]`);

  //enter name
  await page.type(`input[aria-label="Your name"]`, 'Bot');

  //click on ask to join button
  await page.click(
    `button[class="VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-k8QpJ VfPpkd-LgbsSe-OWXEXe-dgl2Hf nCP5yc AjY5Oe DuMIQc LQeN7 jEvJdc QJgqC"]`
  );

  const stream = await getStream(page, { audio: true, video: true, mimeType: "video/webm" });
  console.log("recording");

  stream.pipe(file);

  const recorder = new PuppeteerScreenRecorder.PuppeteerScreenRecorder(page);
  await recorder.start('./report/video/simple.webm'); // supports extension - mp4, avi, webm and mov

  setTimeout(async () => {
    await recorder.stop();
    await stream.destroy();
    file.close();
    console.log("finished");
    await browser.close();
  }, 15000)

})();`

**Comment by SamuelScheit** [comment]
You are using the default puppeteer launch method, although you should use the one from the package:
```js
import { getStream, launch } from "puppeteer-stream";

const browser = await launch({
    headless: false,
    defaultViewport: null,
    devtools: false,
    args: [
    "--window-size=1920,1080",
    "--window-position=1921,0",
    "--autoplay-policy=no-user-gesture-required",
    ],
    ignoreDefaultArgs: ["--mute-audio"],
    executablePath: executablePath(),
});
...
```
