### ISSUE TITLE
Crackling audio when streaming recorded video from puppeteer-stream

### ISSUE THREAD

**Issue by paulnen** [SamuelScheit/puppeteer-stream#91]
We're facing this issue and we were wondering if you had any insight on what the issue might be.

1. Screen recording via puppeteer-stream
2. Save the video locally
3. Convert the file from /webm to mp4
4. Call ffmpeg to push the stream to Youtube

- **Actual result:** perfect video playback, but audio crackles. 
- **Expected:** audio works without crackling

Notes: 
1. When playing the recorded file on a local machine before streaming, the audio works fine
2. When using a file that was not recorded through puppeteer-stream, the audio works fine
3. When Converting the file to FLV, the audio doesn't work

Here are the ffmpeg config settings currently used: 
const settings = {
  audio: true, // whether or not to enable audio
  video: true, // whether or not to enable video
  audioBitsPerSecond: 1200000, // The chosen bitrate for the audio component of the media.
  videoBitsPerSecond: 3200000, // The chosen bitrate for the video component of the media.
  frameSize: 20, // The number of milliseconds to record into each packet.
  videoConstraints: {
    mandatory: {
      minWidth: 1920,
      minHeight: 1080,
      maxWidth: 1920,
      maxHeight: 1080
    }
  }
};

Would appreciate any help / being pointed in the right direction. Thanks again for a great library!

**Comment by paulnen** [comment]
Found the solution: 

puppeteer-stream `audio sample rate `= 48000

Changed the `audio sample rate` on ffmpeg to 44100

**Comment by farzadso** [comment]
@xjchan Do something like this:

```
const stream = await getStream(page, {
    audio: true,
    video: true,
    videoConstraints: {
      mandatory: {
        minWidth: 1920,
        minHeight: 1080,
    audioConstraints: {
      mandatory: {
        sampleRate: { exact: 48000 },
      },
    },
  });
```

And make the change to `ffmpeg` too:

```
const ffmpeg = exec(
    `ffmpeg -y -i - -r 60 -vf "scale=1920:1080" -c:v libx264 -c:a aac -ar 48000 output.mp4`
  );
```
