### ISSUE TITLE
Not working with "createIncognitoBrowserContext"

### ISSUE THREAD

**Issue by stramanu** [SamuelScheit/puppeteer-stream#92]
It doesn't seem to work in incognito mode. It records a blank video

**Comment by SamuelScheit** [comment]
It seems like chromium does not allow extensions to be run in incognito mode by default.
![](https://www.addictivetips.com/app/uploads/2018/12/chrome-ext-incognito.jpg)

You would need to go to the `chrome://extensions` page and [allow the puppeteer-stream extension in incognito mode](https://stackoverflow.com/questions/27534688/enabling-chrome-extension-in-incognito-mode-via-cli-flags).

**Comment by SamuelScheit** [comment]
I've added a `allowIncognito` option to automatically enable the extension in incognito mode.
You can pass it as an option in the launch method:
```ts
const browser = await launch({
    // ...
    devtools: true,
});
``
